### PR TITLE
Adds sample file from example

### PR DESCRIPTION
**Pull request by frankcash**
The [blogpost](https://aws.amazon.com/blogs/compute/better-together-amazon-ecs-and-aws-lambda/) contains a sample config file which is missing.  I added `config.sample.js` to mock what it should be.  People can edit their config and then configure it for themselves!

### CODE REVIEW

**Comment by banjoman** [comment]
Just what I was looking for, otherwise the tutorial was unfollowable. @glez-aws, review please? 🙏

**Review by glez-aws — APPROVED** [review]
Thanks!

**Comment by glez-aws** [comment]
Thanks for adding the sample (and for the reminder) and sorry for the delay!

**Comment by frankcash** [comment]
💯

**Pull request merged**
